# Generated by Django 5.2.8 on 2026-01-18 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresherprofile',
            name='education',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fresherprofile',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fresherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
