# Generated by Django 5.2.8 on 2026-01-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshers', '0002_alter_fresherprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresherprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
