# Generated by Django 5.2.8 on 2026-01-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshers', '0003_alter_fresherprofile_id_alter_jobapplication_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
